#!/usr/bin/env bash
echo"==create bucket"
if [ -z "$1" ]; then
  echo "There needs to be Bucket Name"
  exit 1
  
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region us-east-1 \
--query Location \
--output text
# if want to make bucket in any other region add location constraint
# create-bucket-configuration="LocationConstraint=ca-central-1" 
