AWSTemplateFormatVersion: "2010-09-09"
Description: Launch a simple ec2 
Parameters:
  VpcID:
    Type: String
    Default: vpc-00a09c5b31a47a53e
  ImageID:
    Type: String
    Default: ami-0b07bdf22b8cdc061
  SubnetID:
    Type: String
    Default: subnet-00c823ed597a378aa
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageID
      SubnetId: !Ref SubnetID
      